// SPDX-FileCopyrightText: 2026 ETH Zurich and University of Bologna
//
// SPDX-License-Identifier: Apache-2.0

// XRT C++ testbench for the XDNA2 (AIE2p) platform.
// Loads network.xclbin produced by aiecc.py, runs the MLIR_AIE kernel,
// reads back outputs and compares against golden reference values.
// Output format: "Errors: X out of Y" (required by output_parser.py).
//
// Inputs and outputs are addressed individually: N_INPUTS input vectors
// of N_ELEMENTS_INPUT{i} elements each, N_OUTPUTS output vectors of
// N_ELEMENTS_OUTPUT{i} elements each. This generalizes naturally to the
// chunked I/O produced by XDNA2SpatialSplitPass when num_cores >= 2.

#include <cmath>
#include <cstdint>
#include <cstring>
#include <fstream>
#include <iomanip>
#include <iostream>
#include <stdexcept>
#include <string>
#include <vector>

#include "xrt/xrt_bo.h"
#include "xrt/xrt_device.h"
#include "xrt/xrt_hw_context.h"
#include "xrt/xrt_kernel.h"

// Generated by Deeploy's generateNetwork_xdna2.py:
//   testinputs.h  – N_INPUTS, N_ELEMENTS_INPUT{i}, testInputVector{i},
//                   testInputVector[N_INPUTS] (array of pointers)
//   testoutputs.h – N_OUTPUTS, N_ELEMENTS_OUTPUT{i}, testOutputVector{i},
//                   testOutputVector[N_OUTPUTS]
#include "testinputs.h"
#include "testoutputs.h"

// ---------------------------------------------------------------------------
// BF16 helpers
// ---------------------------------------------------------------------------
static float bf16_to_float(uint16_t bf16) {
  uint32_t f32_bits = static_cast<uint32_t>(bf16) << 16;
  float f;
  std::memcpy(&f, &f32_bits, sizeof(f));
  return f;
}

static bool bf16_nearly_equal(uint16_t a, uint16_t b,
                              unsigned int tolerance_ulps = 1,
                              float rtol = 0.0f, float atol = 0.0f) {
  float fa = bf16_to_float(a);
  float fb = bf16_to_float(b);
  float diff = std::fabs(fa - fb);

  uint16_t ref_exp = (b >> 7) & 0xFF;
  float ulp;
  if (ref_exp == 0)
    ulp = std::ldexp(1.0f, -133);
  else
    ulp = std::ldexp(1.0f, static_cast<int>(ref_exp) - 127 - 7);

  float tol = std::fmax(atol + rtol * std::fabs(fb), ulp * tolerance_ulps);
  return diff <= tol;
}

// ---------------------------------------------------------------------------
// Per-chunk size table (compile-time, generated from testinputs/outputs.h
// macros). Indexed by 0 .. N_INPUTS-1 / 0 .. N_OUTPUTS-1.
// ---------------------------------------------------------------------------
#define _N_ELEMS_INPUT(i) N_ELEMENTS_INPUT##i
#define _N_ELEMS_OUTPUT(i) N_ELEMENTS_OUTPUT##i

// Generate the size tables. We support up to 32 inputs/outputs which is
// the maximum AIE core count on XDNA2.
static constexpr size_t kInputElems[] = {
#define _ELT(i) _N_ELEMS_INPUT(i),
#if N_INPUTS >= 1
    _ELT(0)
#endif
#if N_INPUTS >= 2
        _ELT(1)
#endif
#if N_INPUTS >= 3
            _ELT(2)
#endif
#if N_INPUTS >= 4
                _ELT(3)
#endif
#if N_INPUTS >= 5
                    _ELT(4) _ELT(5) _ELT(6) _ELT(7)
#endif
#if N_INPUTS >= 9
                        _ELT(8) _ELT(9) _ELT(10) _ELT(11) _ELT(12) _ELT(13)
                            _ELT(14) _ELT(15)
#endif
#if N_INPUTS >= 17
                                _ELT(16) _ELT(17) _ELT(18) _ELT(19) _ELT(20)
                                    _ELT(21) _ELT(22) _ELT(23) _ELT(24) _ELT(25)
                                        _ELT(26) _ELT(27) _ELT(28) _ELT(29)
                                            _ELT(30) _ELT(31)
#endif
#undef _ELT
};

static constexpr size_t kOutputElems[] = {
#define _ELT(i) _N_ELEMS_OUTPUT(i),
#if N_OUTPUTS >= 1
    _ELT(0)
#endif
#if N_OUTPUTS >= 2
        _ELT(1)
#endif
#if N_OUTPUTS >= 3
            _ELT(2)
#endif
#if N_OUTPUTS >= 4
                _ELT(3)
#endif
#if N_OUTPUTS >= 5
                    _ELT(4) _ELT(5) _ELT(6) _ELT(7)
#endif
#if N_OUTPUTS >= 9
                        _ELT(8) _ELT(9) _ELT(10) _ELT(11) _ELT(12) _ELT(13)
                            _ELT(14) _ELT(15)
#endif
#if N_OUTPUTS >= 17
                                _ELT(16) _ELT(17) _ELT(18) _ELT(19) _ELT(20)
                                    _ELT(21) _ELT(22) _ELT(23) _ELT(24) _ELT(25)
                                        _ELT(26) _ELT(27) _ELT(28) _ELT(29)
                                            _ELT(30) _ELT(31)
#endif
#undef _ELT
};

// ---------------------------------------------------------------------------
// Read the NPU instruction binary produced by aiecc.py
// ---------------------------------------------------------------------------
static std::vector<uint32_t> read_instr_binary(const std::string &path) {
  std::ifstream file(path, std::ios::binary);
  if (!file.is_open()) {
    throw std::runtime_error("Cannot open instruction file: " + path);
  }
  file.seekg(0, std::ios::end);
  size_t byte_size = file.tellg();
  file.seekg(0, std::ios::beg);

  std::vector<uint32_t> instr(byte_size / sizeof(uint32_t));
  file.read(reinterpret_cast<char *>(instr.data()), byte_size);
  return instr;
}

int main(int argc, char **argv) {
  std::string bin_dir;
  {
    std::string argv0(argv[0]);
    auto sep = argv0.rfind('/');
    bin_dir = (sep == std::string::npos) ? "." : argv0.substr(0, sep);
  }
  std::string xclbin_path = bin_dir + "/network.xclbin";
  std::string instr_path = bin_dir + "/npu_insts.bin";

  bool verbose = false;
  for (int i = 1; i < argc; ++i) {
    std::string arg = argv[i];
    if (arg == "-v" || arg == "--verbose" || arg == "-vv") {
      verbose = true;
    }
  }
  if (argc >= 2 && argv[1][0] != '-')
    xclbin_path = argv[1];
  if (argc >= 3 && argv[2][0] != '-')
    instr_path = argv[2];

  // 1. Open device, register xclbin, build kernel
  auto device = xrt::device(0);
  auto xclbin = xrt::xclbin(xclbin_path);
  device.register_xclbin(xclbin);
  xrt::hw_context context(device, xclbin.get_uuid());
  auto kernel = xrt::kernel(context, "MLIR_AIE");

  // 2. Read NPU instruction binary
  std::vector<uint32_t> instr_v = read_instr_binary(instr_path);
  size_t n_instr = instr_v.size();

  constexpr size_t elem_size = sizeof(uint16_t); // BF16 = 2 bytes

  // 3. Allocate XRT buffers.
  //    Kernel arg layout (matches aiecc.py output):
  //      0: opcode  1: bo_instr  2: instr_len
  //      3..3+N_INPUTS-1:                           inputs
  //      3+N_INPUTS..3+N_INPUTS+N_OUTPUTS-1:        outputs
  //      3+N_INPUTS+N_OUTPUTS:                      ctrlpkts
  //      3+N_INPUTS+N_OUTPUTS+1:                    trace
  constexpr unsigned int n_data_args = N_INPUTS + N_OUTPUTS;
  constexpr unsigned int ctrlpkts_gid = 3u + n_data_args;
  constexpr unsigned int trace_gid = ctrlpkts_gid + 1u;

  auto bo_instr = xrt::bo(device, n_instr * sizeof(uint32_t),
                          XCL_BO_FLAGS_CACHEABLE, kernel.group_id(1));

  std::vector<xrt::bo> bo_inputs;
  bo_inputs.reserve(N_INPUTS);
  for (unsigned int i = 0; i < N_INPUTS; ++i) {
    bo_inputs.emplace_back(device, kInputElems[i] * elem_size,
                           XRT_BO_FLAGS_HOST_ONLY, kernel.group_id(3u + i));
  }

  std::vector<xrt::bo> bo_outputs;
  bo_outputs.reserve(N_OUTPUTS);
  for (unsigned int i = 0; i < N_OUTPUTS; ++i) {
    bo_outputs.emplace_back(device, kOutputElems[i] * elem_size,
                            XRT_BO_FLAGS_HOST_ONLY,
                            kernel.group_id(3u + N_INPUTS + i));
  }

  auto bo_ctrlpkts =
      xrt::bo(device, 8, XRT_BO_FLAGS_HOST_ONLY, kernel.group_id(ctrlpkts_gid));

  constexpr size_t trace_alloc =
      TRACE_BUFFER_SIZE > 0 ? TRACE_BUFFER_SIZE * 4 : 1;
  auto bo_trace = xrt::bo(device, trace_alloc, XRT_BO_FLAGS_HOST_ONLY,
                          kernel.group_id(trace_gid));

  if constexpr (TRACE_BUFFER_SIZE > 0) {
    std::memset(bo_trace.map<void *>(), 0, trace_alloc);
    bo_trace.sync(XCL_BO_SYNC_BO_TO_DEVICE);
  }

  // 4. Copy host data into device buffers
  std::memcpy(bo_instr.map<uint32_t *>(), instr_v.data(),
              n_instr * sizeof(uint32_t));
  bo_instr.sync(XCL_BO_SYNC_BO_TO_DEVICE);

  for (unsigned int i = 0; i < N_INPUTS; ++i) {
    std::memcpy(bo_inputs[i].map<void *>(), testInputVector[i],
                kInputElems[i] * elem_size);
    bo_inputs[i].sync(XCL_BO_SYNC_BO_TO_DEVICE);
  }

  // 5. Launch kernel using set_arg (handles arbitrary arity)
  // JUNGVI: TODO: Collect runtime and display it
  // JUNGVI: TODO: Enable warmup iterations
  auto run = xrt::run(kernel);
  unsigned int arg_idx = 0;
  unsigned int opcode = 3;
  run.set_arg(arg_idx++, opcode);
  run.set_arg(arg_idx++, bo_instr);
  run.set_arg(arg_idx++, static_cast<uint32_t>(n_instr));
  for (auto &bo : bo_inputs)
    run.set_arg(arg_idx++, bo);
  for (auto &bo : bo_outputs)
    run.set_arg(arg_idx++, bo);
  run.set_arg(arg_idx++, bo_ctrlpkts);
  run.set_arg(arg_idx++, bo_trace);
  run.start();
  run.wait();

  // 6. Sync outputs back and compare against golden
  for (auto &bo : bo_outputs)
    bo.sync(XCL_BO_SYNC_BO_FROM_DEVICE);

  int errors = 0;
  size_t total_elems = 0;
  for (unsigned int o = 0; o < N_OUTPUTS; ++o) {
    const uint16_t *hw_out = bo_outputs[o].map<const uint16_t *>();
    const uint16_t *golden_out =
        static_cast<const uint16_t *>(testOutputVector[o]);
    const size_t n = kOutputElems[o];
    total_elems += n;
    for (size_t i = 0; i < n; ++i) {
      bool match =
          bf16_nearly_equal(hw_out[i], golden_out[i], BF16_TOLERANCE_ULPS);
      if (!match) {
        ++errors;
        if (errors <= 10) {
          std::cerr << "  Mismatch out[" << o << "][" << i
                    << "]: hw=" << bf16_to_float(hw_out[i]) << " (0x"
                    << std::hex << hw_out[i] << std::dec << ")"
                    << "  ref=" << bf16_to_float(golden_out[i]) << " (0x"
                    << std::hex << golden_out[i] << std::dec << ")"
                    << "  diff="
                    << std::fabs(bf16_to_float(hw_out[i]) -
                                 bf16_to_float(golden_out[i]))
                    << "\n";
        }
      }
      if (verbose) {
        float hw_f = bf16_to_float(hw_out[i]);
        float ref_f = bf16_to_float(golden_out[i]);
        std::cout << "out[" << o << "][" << i << "] hw=" << hw_f
                  << "  ref=" << ref_f << "  diff=" << std::fabs(hw_f - ref_f)
                  << (match ? "" : "  *** MISMATCH") << "\n";
      }
    }
  }

  // Output format required by testUtils/core/output_parser.py
  std::cout << "Errors: " << errors << " out of " << total_elems << "\n";

  // 7. Read back trace data and write to trace.txt
  if constexpr (TRACE_BUFFER_SIZE > 0) {
    bo_trace.sync(XCL_BO_SYNC_BO_FROM_DEVICE);

    const uint32_t *trace_data = bo_trace.map<const uint32_t *>();
    size_t trace_words = TRACE_BUFFER_SIZE / sizeof(uint32_t);

    std::string trace_path = bin_dir + "/trace.txt";
    std::ofstream trace_file(trace_path);
    if (trace_file.is_open()) {
      for (size_t i = 0; i < trace_words; ++i) {
        if (trace_data[i] != 0) {
          trace_file << std::hex << std::setfill('0') << std::setw(8)
                     << trace_data[i] << "\n";
        }
      }
      trace_file.close();
      std::cout << "Trace written to " << trace_path << "\n";
    } else {
      std::cerr << "Warning: could not open " << trace_path << " for writing\n";
    }
  }

  return (errors == 0) ? 0 : 1;
}
