# SPDX-FileCopyrightText: 2025 ETH Zurich and University of Bologna
#
# SPDX-License-Identifier: Apache-2.0
"""XDNA2 network generation script.

Replaces the generic ``generateNetwork.py`` for the XDNA2 platform.
Instead of emitting C code it:

1. Loads the ONNX model and npz test-data.
2. Prepares the XDNA2Deployer (type checking + graph binding).
3. Emits ``testinputs.h`` and ``testoutputs.h`` with raw BF16 uint16_t arrays.
4. Calls ``deployer.generateMLIR()`` and writes ``network.mlir``.
"""

import os

import numpy as np
import onnx
import onnx_graphsurgeon as gs
from testUtils.platformMapping import mapDeployer
from testUtils.testRunner import TestGeneratorArgumentParser

from Deeploy.AbstractDataTypes import PointerClass
from Deeploy.CommonExtensions.DataTypes import bfloat16_t
from Deeploy.DeeployTypes import TopologyOptimizer
from Deeploy.EngineExtension.NetworkDeployers.EngineColoringDeployer import EngineColoringDeployerWrapper
from Deeploy.Logging import DEFAULT_LOGGER as log
from Deeploy.MemoryLevelExtension.MemoryLevels import MemoryHierarchy, MemoryLevel
from Deeploy.MemoryLevelExtension.NetworkDeployers.MemoryLevelDeployer import MemoryDeployerWrapper
from Deeploy.Targets.XDNA2.Platform import MemoryXDNA2Platform, XDNA2AIECoreDataMover, XDNA2AIECoreEngine, \
    XDNA2Mapping, XDNA2ShimTileDataMover
from Deeploy.Targets.XDNA2.TopologyOptimizationPasses.DefaultConstantDataMoveAnnotationPass import \
    XDNA2DefaultConstantDataMoveAnnotationPass
from Deeploy.Targets.XDNA2.TopologyOptimizationPasses.DefaultInputDataMoveAnnotationPass import \
    XDNA2DefaultIODataMoveAnnotationPass
from Deeploy.Targets.XDNA2.TopologyOptimizationPasses.SpatialSplitPass import XDNA2SpatialSplitPass
from Deeploy.TilingExtension.TilerExtension import TilerDeployerWrapper


def _tilingScheduler(graph: gs.Graph):
    return [[node] for node in graph.nodes]


def _float32_to_bf16_uint16(arr: np.ndarray) -> np.ndarray:
    """Convert a float32 numpy array to an array of BF16 bit patterns (uint16_t).

    Uses round-to-nearest-even (the standard IEEE 754 rounding mode).
    """
    f32 = arr.astype(np.float32)
    raw = f32.view(np.uint32)
    # Standard round-to-nearest-even: add 0x7FFF + BF16_LSB to the full word,
    # then truncate.  The 0x7FFF biases values just below the midpoint to
    # round down, while adding the BF16 LSB provides tie-breaking to even.
    bf16_lsb = (raw >> 16) & 1
    raw = raw + np.uint32(0x7FFF) + bf16_lsb
    bf16 = (raw >> 16).astype(np.uint16)
    return bf16


def _bf16_to_float32(bf16: np.ndarray) -> np.ndarray:
    """Convert an array of BF16 uint16 bit patterns back to float32."""
    f32_bits = bf16.astype(np.uint32) << 16
    return f32_bits.view(np.float32)


def _generate_xdna2_inputs_header(input_arrays: list) -> str:
    """Generate testinputs.h with one entry per logical input.

    Logical inputs (the original ONNX graph inputs, before any spatial
    split) are what the host bo allocation matches. The deployer collapses
    spatial-split chunks back to logical args at the runtime_sequence
    boundary, so the host only sees the originals.
    """
    lines = []
    lines.append("// SPDX-FileCopyrightText: 2026 ETH Zurich and University of Bologna")
    lines.append("// SPDX-License-Identifier: Apache-2.0")
    lines.append("// Auto-generated by generateNetwork_xdna2.py — do not edit.")
    lines.append("#pragma once")
    lines.append("#include <stdint.h>")
    lines.append("")
    lines.append(f"#define N_INPUTS {len(input_arrays)}u")
    lines.append("")

    vec_names = []
    for idx, arr in enumerate(input_arrays):
        bf16 = _float32_to_bf16_uint16(arr.flatten())
        n = len(bf16)
        name = f"testInputVector{idx}"
        vec_names.append(name)
        hex_vals = ", ".join(f"0x{v:04x}u" for v in bf16)
        lines.append(f"static const uint16_t {name}[{n}] = {{{hex_vals}}};")
        lines.append(f"#define N_ELEMENTS_INPUT{idx} {n}u")
        lines.append("")

    lines.append(f"static const void *testInputVector[{len(vec_names)}] = {{")
    lines.append("    " + ", ".join(f"(const void *){n}" for n in vec_names))
    lines.append("};")
    lines.append("")
    return "\n".join(lines)


def _generate_xdna2_outputs_header(output_arrays: list, tolerance_ulps: int = 1) -> str:
    """Generate testoutputs.h with one entry per logical output."""
    lines = []
    lines.append("// SPDX-FileCopyrightText: 2026 ETH Zurich and University of Bologna")
    lines.append("// SPDX-License-Identifier: Apache-2.0")
    lines.append("// Auto-generated by generateNetwork_xdna2.py — do not edit.")
    lines.append("#pragma once")
    lines.append("#include <stdint.h>")
    lines.append("")
    lines.append(f"#define BF16_TOLERANCE_ULPS {tolerance_ulps}u")
    lines.append(f"#define N_OUTPUTS {len(output_arrays)}u")
    lines.append("")

    vec_names = []
    for idx, arr in enumerate(output_arrays):
        bf16 = _float32_to_bf16_uint16(arr.flatten())
        n = len(bf16)
        name = f"testOutputVector{idx}"
        vec_names.append(name)
        hex_vals = ", ".join(f"0x{v:04x}u" for v in bf16)
        lines.append(f"static const uint16_t {name}[{n}] = {{{hex_vals}}};")
        lines.append(f"#define N_ELEMENTS_OUTPUT{idx} {n}u")
        lines.append("")

    lines.append(f"static const void *testOutputVector[{len(vec_names)}] = {{")
    lines.append("    " + ", ".join(f"(const void *){n}" for n in vec_names))
    lines.append("};")
    lines.append("")
    return "\n".join(lines)


def generateNetworkXDNA2(args):
    log.debug("Arguments: %s", args)

    onnx_graph = onnx.load_model(f'{args.dir}/network.onnx')
    graph = gs.import_onnx(onnx_graph)

    inputs_npz = np.load(f'{args.dir}/inputs.npz')
    outputs_npz = np.load(f'{args.dir}/outputs.npz')

    test_inputs = [inputs_npz[x] for x in inputs_npz.files]
    test_outputs = [outputs_npz[x] for x in outputs_npz.files]

    inputTypes = {}
    inputOffsets = {}

    # Number of cores is needed early to register types for the per-chunk
    # graph inputs that XDNA2SpatialSplitPass will create.
    _num_cores_for_types = int(getattr(args, 'num_cores', None) or 1)

    for index, (name, values) in enumerate(zip(inputs_npz.files, test_inputs)):
        if np.prod(values.shape) == 0:
            continue
        # Force bfloat16_t — BF16 test data stored as float32 in npz would be
        # inferred as float32_t by minimalFloatType, but the XDNA2 kernel
        # requires bfloat16_t inputs.
        # JUNGVI: TODO: Align minimalFloatType to properly handle bf16 and don't force types.
        inputTypes[f"input_{index}"] = PointerClass(bfloat16_t)
        inputOffsets[f"input_{index}"] = 0
        # Register chunk variants as well so _createIOBindings can resolve
        # them after XDNA2SpatialSplitPass has renamed graph.inputs.
        if _num_cores_for_types >= 2:
            for chunk in range(_num_cores_for_types):
                inputTypes[f"input_{index}_c{chunk}"] = PointerClass(bfloat16_t)
                inputOffsets[f"input_{index}_c{chunk}"] = 0

    _DEEPLOYSTATEDIR = os.path.join(args.dumpdir, "deeployStates")

    # JUNGVI: TODO: Extend with the whole NPU array
    # Define memory hierarchy: L1 (AIE core local) and L3 (shared)
    l1_size = int(getattr(args, 'l1', None) or 64000)  # 64KB default
    l3_size = int(getattr(args, 'l3', None) or 128 * 1024 * 1024)  # 128MB default
    num_cores = int(getattr(args, 'num_cores', None) or 1)
    aie_row = int(getattr(args, 'aie_row', None) or 2)

    log.info(f"[XDNA2] Using MemoryXDNA2Platform with L1={l1_size}, L3={l3_size}, "
             f"num_cores={num_cores}, row={aie_row}")

    l1_level = MemoryLevel("L1", neighbourNames = ["L3"], size = l1_size)
    l3_level = MemoryLevel("L3", neighbourNames = ["L1"], size = l3_size)
    memory_hierarchy = MemoryHierarchy([l1_level, l3_level])
    memory_hierarchy.setDefaultMemoryLevel("L3")  # Tensors default to L3

    coreEngines = [XDNA2AIECoreEngine(col = i, row = aie_row) for i in range(num_cores)]

    # One data mover per shim tile and one per AIE core
    dataMoverEngines = [XDNA2ShimTileDataMover(col = i) for i in range(num_cores)] + \
                       [XDNA2AIECoreDataMover(col = i, row = aie_row) for i in range(num_cores)]

    mem_platform = MemoryXDNA2Platform(
        memoryHierarchy = memory_hierarchy,
        defaultTargetMemoryLevel = l1_level,
        engines = coreEngines,
        dataMoverEngines = dataMoverEngines,
    )

    loweringOptimizer = TopologyOptimizer([
        XDNA2DefaultIODataMoveAnnotationPass(),
        XDNA2DefaultConstantDataMoveAnnotationPass(),
        XDNA2SpatialSplitPass(axis = 0),
    ])

    deployer = mapDeployer(mem_platform,
                           graph,
                           inputTypes,
                           loweringOptimizer = loweringOptimizer,
                           scheduler = _tilingScheduler,
                           deeployStateDir = _DEEPLOYSTATEDIR,
                           inputOffsets = inputOffsets)

    # Always wrap so the engine-aware setter fires and binding goes through
    # the engine-coloring _selectEngine path. With a single AIE engine
    # everything trivially colors to that one engine, matching the
    # pre-refactor single-core behavior.
    deployer = EngineColoringDeployerWrapper(deployer)

    # Wrap with MemoryDeployerWrapper (default memory-level annotation).
    # The data-mover hint pivot lives in XDNA2Deployer.frontEnd() — see
    # _extractDataMoverToContext.
    deployer = MemoryDeployerWrapper(deployer)

    # Wrap with TilerDeployerWrapper (adds tiling)
    deployer = TilerDeployerWrapper(deployer, workDir = _DEEPLOYSTATEDIR)

    # Enable tracing if requested
    enableTrace = getattr(args, 'trace', False)
    if enableTrace:
        traceBufferSize = int(getattr(args, 'trace_buffer_size', None) or 8192)
        deployer.enableTrace = True
        deployer.traceBufferSize = traceBufferSize
        log.info(f"[XDNA2] Tracing enabled (buffer_size={traceBufferSize})")

    deployer.frontEnd()
    deployer.midEnd()
    deployer.prepared = True
    log.info("[XDNA2] Tiling completed, proceeding with MLIR generation")

    # Create output directory
    os.makedirs(args.dumpdir, exist_ok = True)

    # Write testinputs.h (raw BF16 bit patterns as uint16_t)
    testInputStr = _generate_xdna2_inputs_header(test_inputs)
    # Append trace buffer size define so the host binary knows whether to
    # allocate a trace buffer and how large it should be.
    if enableTrace:
        testInputStr += f"#define TRACE_BUFFER_SIZE {traceBufferSize}u\n"
    else:
        testInputStr += "#define TRACE_BUFFER_SIZE 0u\n"
    with open(f'{args.dumpdir}/testinputs.h', 'w') as f:
        f.write(testInputStr)

    # Determine BF16 comparison tolerance (in ULPs) based on operator types.
    _APPROX_OPS = {'Silu', 'Gelu', 'Sigmoid', 'Tanh', 'Softmax', 'LayerNormalization'}
    op_types = {node.op for node in graph.nodes}
    tolerance_ulps = 40 if op_types & _APPROX_OPS else 1

    # Write testoutputs.h (raw BF16 bit patterns as uint16_t)
    testOutputStr = _generate_xdna2_outputs_header(test_outputs, tolerance_ulps = tolerance_ulps)
    with open(f'{args.dumpdir}/testoutputs.h', 'w') as f:
        f.write(testOutputStr)

    # Write network.mlir
    mlir_str = deployer.generateMLIR()
    with open(f'{args.dumpdir}/network.mlir', 'w') as f:
        f.write(mlir_str)

    log.info(f"[XDNA2] Generated: testinputs.h, testoutputs.h, network.mlir -> {args.dumpdir}")


if __name__ == '__main__':
    parser = TestGeneratorArgumentParser(tiling_arguments = True,
                                         description = "Deeploy XDNA2 Code Generation Utility.")
    parser.add_argument('--trace',
                        action = 'store_true',
                        default = False,
                        help = 'Enable execution tracing in the generated MLIR')
    parser.add_argument('--trace-buffer-size',
                        type = int,
                        default = 8192,
                        help = 'Trace buffer size in bytes (default: 8192)')
    parser.add_argument('--num-cores',
                        type = int,
                        default = 1,
                        help = 'Number of AIE compute cores to spatially split across (default: 1)')
    parser.add_argument('--aie-row',
                        type = int,
                        default = 2,
                        help = 'AIE row index for the compute cores (default: 2)')
    args, _ = parser.parse_known_args()

    if args.platform != 'XDNA2':
        parser.error(f"This script is for the XDNA2 platform. Got: {args.platform}")

    generateNetworkXDNA2(args)
