# SPDX-FileCopyrightText: 2025 ETH Zurich and University of Bologna
#
# SPDX-License-Identifier: Apache-2.0
"""XDNA2 network generation script.

Replaces the generic ``generateNetwork.py`` for the XDNA2 platform.
Instead of emitting C code it:

1. Loads the ONNX model and npz test-data.
2. Prepares the XDNA2Deployer (type checking + graph binding).
3. Emits ``testinputs.h`` and ``testoutputs.h`` with raw BF16 uint16_t arrays.
4. Calls ``deployer.generateMLIR()`` and writes ``network.mlir``.
"""

import os
from typing import Literal, Optional

import numpy as np
import onnx
import onnx_graphsurgeon as gs
from testUtils.platformMapping import mapDeployer
from testUtils.testRunner import TestGeneratorArgumentParser

from Deeploy.AbstractDataTypes import PointerClass
from Deeploy.CommonExtensions.DataTypes import bfloat16_t
from Deeploy.DeeployTypes import TopologyOptimizer
from Deeploy.EngineExtension.NetworkDeployers.EngineColoringDeployer import EngineColoringDeployerWrapper
from Deeploy.Logging import DEFAULT_LOGGER as log
from Deeploy.MemoryLevelExtension.MemoryLevels import MemoryHierarchy, MemoryLevel
from Deeploy.MemoryLevelExtension.NetworkDeployers.MemoryLevelDeployer import MemoryDeployerWrapper
from Deeploy.Targets.XDNA2.Platform import NPU2_AIE_ROW_OFFSET, NPU2_NUM_AIE_ROWS, NPU2_NUM_COLS, MemoryXDNA2Platform, \
    XDNA2AIECoreDataMover, XDNA2AIECoreEngine, XDNA2MemTileDataMover, XDNA2MemTileExecutionEngine, \
    XDNA2ShimTileDataMover
from Deeploy.Targets.XDNA2.TopologyOptimizationPasses.DefaultConstantDataMoveAnnotationPass import \
    XDNA2DefaultConstantDataMoveAnnotationPass
from Deeploy.Targets.XDNA2.TopologyOptimizationPasses.DefaultInputDataMoveAnnotationPass import \
    XDNA2DefaultIODataMoveAnnotationPass
from Deeploy.Targets.XDNA2.TopologyOptimizationPasses.HybridElementwiseSpatialSplitPass import \
    XDNA2HybridElementwiseSpatialSplitPass
from Deeploy.TilingExtension.TilerExtension import TilerDeployerWrapper


def _tilingScheduler(graph: gs.Graph):
    return [[node] for node in graph.nodes]


def _float32_to_bf16_uint16(arr: np.ndarray) -> np.ndarray:
    """Convert a float32 numpy array to an array of BF16 bit patterns (uint16_t).

    Uses round-to-nearest-even (the standard IEEE 754 rounding mode).
    """
    f32 = arr.astype(np.float32)
    raw = f32.view(np.uint32)
    # Standard round-to-nearest-even: add 0x7FFF + BF16_LSB to the full word,
    # then truncate.  The 0x7FFF biases values just below the midpoint to
    # round down, while adding the BF16 LSB provides tie-breaking to even.
    bf16_lsb = (raw >> 16) & 1
    raw = raw + np.uint32(0x7FFF) + bf16_lsb
    bf16 = (raw >> 16).astype(np.uint16)
    return bf16


def _bf16_to_float32(bf16: np.ndarray) -> np.ndarray:
    """Convert an array of BF16 uint16 bit patterns back to float32."""
    f32_bits = bf16.astype(np.uint32) << 16
    return f32_bits.view(np.float32)


# Tensors larger than this are written to .bin sidecars instead of being
# embedded as C++ literals.
_EMBED_THRESHOLD_BYTES = 32 * 1024 * 1024


def _should_use_file_mode(arrays, mode: Literal["auto", "embed", "file"]) -> bool:
    if mode == "file":
        return True
    if mode == "embed":
        return False
    return any(arr.size * 2 > _EMBED_THRESHOLD_BYTES for arr in arrays)


def _emit_embedded_array(name: str, bf16: np.ndarray) -> str:
    hex_vals = ", ".join(f"0x{v:04x}u" for v in bf16)
    return f"static const uint16_t {name}[{len(bf16)}] = {{{hex_vals}}};"


def _generate_xdna2_inputs_header(input_arrays: list,
                                  dump_dir: str,
                                  mode: Literal["auto", "embed", "file"] = "auto",
                                  padded_elem_counts: Optional[list] = None) -> str:
    """Generate testinputs.h with one entry per logical input.

    Logical inputs (the original ONNX graph inputs, before any spatial
    split) are what the host bo allocation matches. The deployer collapses
    spatial-split chunks back to logical args at the runtime_sequence
    boundary, so the host only sees the originals.
    """

    use_file = _should_use_file_mode(input_arrays, mode)
    n_inputs = len(input_arrays)

    lines = []
    lines.append("// SPDX-FileCopyrightText: 2026 ETH Zurich and University of Bologna")
    lines.append("// SPDX-License-Identifier: Apache-2.0")
    lines.append("// Auto-generated by generateNetwork_xdna2.py — do not edit.")
    lines.append("#pragma once")
    lines.append("#include <stddef.h>")
    lines.append("#include <stdint.h>")
    lines.append("")
    lines.append(f"#define N_INPUTS {n_inputs}u")
    if use_file:
        lines.append("#define USE_FILE_INPUTS 1")
    lines.append("")

    # Element counts emitted as a single constexpr table, kInputElems is the LOGICAL size
    elem_counts = [len(_float32_to_bf16_uint16(arr.flatten())) for arr in input_arrays]
    if padded_elem_counts is None:
        padded_elem_counts = list(elem_counts)
    assert len(padded_elem_counts) == n_inputs, (
        f"padded_elem_counts length {len(padded_elem_counts)} != n_inputs {n_inputs}")
    for i, (logical, padded) in enumerate(zip(elem_counts, padded_elem_counts)):
        assert padded >= logical, (f"input {i}: padded size {padded} < logical size {logical}; topology "
                                   f"pass returned a shrinking pad which is never valid")
    lines.append(f"static constexpr size_t kInputElems[{n_inputs}] = {{")
    lines.append("    " + ", ".join(f"{n}u" for n in elem_counts) + "")
    lines.append("};")
    lines.append(f"static constexpr size_t kInputPaddedElems[{n_inputs}] = {{")
    lines.append("    " + ", ".join(f"{n}u" for n in padded_elem_counts) + "")
    lines.append("};")
    lines.append("")

    if use_file:
        # Filename table, main.cpp loops over it in startup.
        filenames = []
        for idx, arr in enumerate(input_arrays):
            bf16 = _float32_to_bf16_uint16(arr.flatten())
            fname = f"input{idx}.bin"
            with open(os.path.join(dump_dir, fname), "wb") as f:
                f.write(bf16.tobytes())
            filenames.append(fname)
        lines.append(f"static const char *const kInputFilenames[{n_inputs}] = {{")
        lines.append("    " + ", ".join(f'"{n}"' for n in filenames))
        lines.append("};")
        lines.append("")
    else:
        # Embed mode, each tensor is a static const array; `testInputVector`
        # is a parallel pointer table indexed at runtime.
        names = []
        for idx, arr in enumerate(input_arrays):
            bf16 = _float32_to_bf16_uint16(arr.flatten())
            name = f"testInputVector{idx}"
            names.append(name)
            lines.append(_emit_embedded_array(name, bf16))
            lines.append("")
        lines.append(f"static const void *const testInputVector[{n_inputs}] = {{")
        lines.append("    " + ", ".join(f"(const void *){n}" for n in names))
        lines.append("};")
        lines.append("")
    return "\n".join(lines)


def _generate_xdna2_outputs_header(output_arrays: list,
                                   dump_dir: str,
                                   tolerance_ulps: int = 1,
                                   mode: Literal["auto", "embed", "file"] = "auto",
                                   padded_elem_counts: Optional[list] = None) -> str:
    """Generate testoutputs.h with one entry per logical output."""
    use_file = _should_use_file_mode(output_arrays, mode)
    n_outputs = len(output_arrays)

    lines = []
    lines.append("// SPDX-FileCopyrightText: 2026 ETH Zurich and University of Bologna")
    lines.append("// SPDX-License-Identifier: Apache-2.0")
    lines.append("// Auto-generated by generateNetwork_xdna2.py — do not edit.")
    lines.append("#pragma once")
    lines.append("#include <stddef.h>")
    lines.append("#include <stdint.h>")
    lines.append("")
    lines.append(f"#define BF16_TOLERANCE_ULPS {tolerance_ulps}u")
    lines.append(f"#define N_OUTPUTS {n_outputs}u")
    if use_file:
        lines.append("#define USE_FILE_OUTPUTS 1")
    lines.append("")

    elem_counts = [len(_float32_to_bf16_uint16(arr.flatten())) for arr in output_arrays]
    if padded_elem_counts is None:
        padded_elem_counts = list(elem_counts)
    assert len(padded_elem_counts) == n_outputs
    for i, (logical, padded) in enumerate(zip(elem_counts, padded_elem_counts)):
        assert padded >= logical, (f"output {i}: padded size {padded} < logical size {logical}")
    lines.append(f"static constexpr size_t kOutputPaddedElems[{n_outputs}] = {{")
    lines.append("    " + ", ".join(f"{n}u" for n in padded_elem_counts) + "")
    lines.append("};")
    lines.append(f"static constexpr size_t kOutputElems[{n_outputs}] = {{")
    lines.append("    " + ", ".join(f"{n}u" for n in elem_counts) + "")
    lines.append("};")
    lines.append("")

    if use_file:
        filenames = []
        for idx, arr in enumerate(output_arrays):
            bf16 = _float32_to_bf16_uint16(arr.flatten())
            fname = f"output{idx}.bin"
            with open(os.path.join(dump_dir, fname), "wb") as f:
                f.write(bf16.tobytes())
            filenames.append(fname)
        lines.append(f"static const char *const kOutputFilenames[{n_outputs}] = {{")
        lines.append("    " + ", ".join(f'"{n}"' for n in filenames))
        lines.append("};")
        lines.append("")
    else:
        names = []
        for idx, arr in enumerate(output_arrays):
            bf16 = _float32_to_bf16_uint16(arr.flatten())
            name = f"testOutputVector{idx}"
            names.append(name)
            lines.append(_emit_embedded_array(name, bf16))
            lines.append("")
        lines.append(f"static const void *const testOutputVector[{n_outputs}] = {{")
        lines.append("    " + ", ".join(f"(const void *){n}" for n in names))
        lines.append("};")
        lines.append("")
    return "\n".join(lines)


def generateNetworkXDNA2(args):
    log.debug("Arguments: %s", args)

    onnx_graph = onnx.load_model(f'{args.dir}/network.onnx')
    graph = gs.import_onnx(onnx_graph)

    inputs_npz = np.load(f'{args.dir}/inputs.npz')
    outputs_npz = np.load(f'{args.dir}/outputs.npz')

    test_inputs = [inputs_npz[x] for x in inputs_npz.files]
    test_outputs = [outputs_npz[x] for x in outputs_npz.files]

    inputTypes = {}
    inputOffsets = {}

    # NPU array shape: how much of the AIE array we activate this run.
    num_col = int(getattr(args, 'num_col', None) or 1)
    num_aie_row = int(getattr(args, 'num_aie_row', None) or 1)
    assert 1 <= num_col <= NPU2_NUM_COLS, f"--num-col must be in [1, {NPU2_NUM_COLS}], got {num_col}"
    assert 1 <= num_aie_row <= NPU2_NUM_AIE_ROWS, (
        f"--num-aie-row must be in [1, {NPU2_NUM_AIE_ROWS}], got {num_aie_row}")
    total_chunks = num_col * num_aie_row

    for index, (name, values) in enumerate(zip(inputs_npz.files, test_inputs)):
        if np.prod(values.shape) == 0:
            continue
        # Force bfloat16_t — BF16 test data stored as float32 in npz would be
        # inferred as float32_t by minimalFloatType, but the XDNA2 kernel
        # requires bfloat16_t inputs.
        # JUNGVI: TODO: Align minimalFloatType to properly handle bf16 and don't force types.
        inputTypes[f"input_{index}"] = PointerClass(bfloat16_t)
        inputOffsets[f"input_{index}"] = 0
        # Chunk variants: the hybrid spatial-split pass renames graph
        # inputs to ``input_{index}_c{col}_g{group}`` where group is 0
        # or 1 depending on per-column geometry. Pre-register every name
        # the pass might emit; unused entries are harmless.
        for col in range(num_col):
            for group in range(2):
                key = f"input_{index}_c{col}_g{group}"
                inputTypes[key] = PointerClass(bfloat16_t)
                inputOffsets[key] = 0

    _DEEPLOYSTATEDIR = os.path.join(args.dumpdir, "deeployStates")

    # Memory sizes (per tile / per shared region).
    l1_size = int(getattr(args, 'l1', None) or 64000)  # 64 KB per AIE tile
    l2_size = int(getattr(args, 'l2', None) or 512 * 1024)  # 512 KB per mem tile
    l3_size = int(getattr(args, 'l3', None) or 42000 * 1024 * 1024)  # 42 GB DRAM

    log.info(f"[XDNA2] Array config: num_col={num_col}, num_aie_row={num_aie_row} "
             f"(total {total_chunks} AIE compute tiles); L1={l1_size}, L2={l2_size}, L3={l3_size}")

    # ---- Memory hierarchy: model the FULL XDNA2 NPU. ----
    # 1 L3 + NPU2_NUM_COLS L2 + NPU2_NUM_COLS×NPU2_NUM_AIE_ROWS L1.
    levels = []
    aie_rows = list(range(NPU2_AIE_ROW_OFFSET, NPU2_AIE_ROW_OFFSET + NPU2_NUM_AIE_ROWS))
    all_l2_names = [f"L2_c{c}" for c in range(NPU2_NUM_COLS)]
    all_l1_names = [f"L1_c{c}r{r}" for c in range(NPU2_NUM_COLS) for r in aie_rows]
    levels.append(MemoryLevel("L3", neighbourNames = all_l2_names + all_l1_names, size = l3_size))
    for c in range(NPU2_NUM_COLS):
        col_l1_names = [f"L1_c{c}r{r}" for r in aie_rows]
        levels.append(MemoryLevel(f"L2_c{c}", neighbourNames = ["L3"] + col_l1_names, size = l2_size))
    for c in range(NPU2_NUM_COLS):
        for r in aie_rows:
            levels.append(MemoryLevel(f"L1_c{c}r{r}", neighbourNames = ["L3", f"L2_c{c}"], size = l1_size))
    memory_hierarchy = MemoryHierarchy(levels)
    memory_hierarchy.setDefaultMemoryLevel("L3")
    l3_level = memory_hierarchy.memoryLevels["L3"]

    # ---- Execution Engines ----
    used_aie_rows = list(range(NPU2_AIE_ROW_OFFSET, NPU2_AIE_ROW_OFFSET + num_aie_row))
    coreEngines = [XDNA2AIECoreEngine(col = c, row = r) for c in range(num_col) for r in used_aie_rows]
    memTileEngines = [XDNA2MemTileExecutionEngine(col = c) for c in range(num_col)]

    # ---- Data Mover Engines ----
    dataMoverEngines: list = []
    for c in range(num_col):
        dataMoverEngines.append(XDNA2ShimTileDataMover(col = c))
        dataMoverEngines.append(XDNA2MemTileDataMover(col = c))
    for c in range(num_col):
        for r in used_aie_rows:
            dataMoverEngines.append(XDNA2AIECoreDataMover(col = c, row = r))

    mem_platform = MemoryXDNA2Platform(
        memoryHierarchy = memory_hierarchy,
        defaultTargetMemoryLevel = l3_level,
        engines = coreEngines + memTileEngines,
        dataMoverEngines = dataMoverEngines,
    )

    # Single arity-aware pass: decides per-column geometry from the op
    # arity and per-column row count R, using the shim's 2-channel-pair
    # budget. Subsumes both the prior shim-direct and mem-tile-only
    # passes.
    loweringOptimizer = TopologyOptimizer([
        XDNA2DefaultIODataMoveAnnotationPass(),
        XDNA2DefaultConstantDataMoveAnnotationPass(),
        XDNA2HybridElementwiseSpatialSplitPass(axis = 0),
    ])

    deployer = mapDeployer(mem_platform,
                           graph,
                           inputTypes,
                           loweringOptimizer = loweringOptimizer,
                           scheduler = _tilingScheduler,
                           deeployStateDir = _DEEPLOYSTATEDIR,
                           inputOffsets = inputOffsets)

    deployer = EngineColoringDeployerWrapper(deployer)
    deployer = MemoryDeployerWrapper(deployer)
    deployer = TilerDeployerWrapper(deployer, workDir = _DEEPLOYSTATEDIR)

    # --trace alone traces every active engine
    # --trace-tiles c0r2,c1r2 narrows to a subset
    enableTrace = getattr(args, 'trace', False)
    if enableTrace:
        traceBufferSize = int(getattr(args, 'trace_buffer_size', None) or 8192)
        traceShimCol = int(getattr(args, 'trace_shim_col', 7))
        deployer.enableTrace = True
        deployer.traceBufferSize = traceBufferSize
        deployer.traceShimCol = traceShimCol
        traceTiles = getattr(args, 'trace_tiles', None)
        if traceTiles:
            knownEngines = {e.name for e in coreEngines}
            requested = {f"AIE_{tok.strip()}" for tok in traceTiles.split(',') if tok.strip()}
            unknown = requested - knownEngines
            if unknown:
                raise SystemExit(f"--trace-tiles names tiles not active in this run: {sorted(unknown)}. "
                                 f"Active engines for num-col={num_col} num-aie-row={num_aie_row}: "
                                 f"{sorted(knownEngines)}.")
            deployer.tracedEngines = requested
            log.info(f"[XDNA2] Tracing enabled (buffer_size={traceBufferSize}, "
                     f"egress_shim_col={traceShimCol}, tiles={sorted(requested)})")
        else:
            log.info(f"[XDNA2] Tracing enabled (buffer_size={traceBufferSize}, "
                     f"egress_shim_col={traceShimCol}, tiles=all)")

    deployer.frontEnd()
    deployer.midEnd()
    deployer.prepared = True
    log.info("[XDNA2] Tiling completed, proceeding with MLIR generation")

    # Create output directory
    os.makedirs(args.dumpdir, exist_ok = True)

    # Write testinputs.h (raw BF16 bit patterns as uint16_t).
    data_mode = getattr(args, 'data_mode', 'auto')
    # Topology passes may have padded graph IO, recover the padded shapes.
    input_padded_sizes, output_padded_sizes = deployer.getLogicalIOPaddedSizes()
    testInputStr = _generate_xdna2_inputs_header(test_inputs,
                                                 args.dumpdir,
                                                 mode = data_mode,
                                                 padded_elem_counts = input_padded_sizes)
    # Append trace buffer size define so the host binary knows whether to
    # allocate a trace buffer and how large it should be.
    if enableTrace:
        testInputStr += f"#define TRACE_BUFFER_SIZE {traceBufferSize}u\n"
    else:
        testInputStr += "#define TRACE_BUFFER_SIZE 0u\n"
    with open(f'{args.dumpdir}/testinputs.h', 'w') as f:
        f.write(testInputStr)

    # Determine BF16 comparison tolerance (in ULPs) based on operator types.
    _APPROX_OPS = {'Silu', 'Gelu', 'Sigmoid', 'Tanh', 'Softmax', 'LayerNormalization'}
    op_types = {node.op for node in graph.nodes}
    tolerance_ulps = 40 if op_types & _APPROX_OPS else 1

    # Write testoutputs.h (raw BF16 bit patterns as uint16_t)
    testOutputStr = _generate_xdna2_outputs_header(test_outputs,
                                                   args.dumpdir,
                                                   tolerance_ulps = tolerance_ulps,
                                                   mode = data_mode,
                                                   padded_elem_counts = output_padded_sizes)
    with open(f'{args.dumpdir}/testoutputs.h', 'w') as f:
        f.write(testOutputStr)

    # Write network.mlir
    mlir_str = deployer.generateMLIR()
    with open(f'{args.dumpdir}/network.mlir', 'w') as f:
        f.write(mlir_str)

    # Report total ops
    total_ops = deployer.numberOfOps(verbose=False)
    log.info(f"[XDNA2] Total Operations: {total_ops}")

    log.info(f"[XDNA2] Generated: testinputs.h, testoutputs.h, network.mlir -> {args.dumpdir}")


if __name__ == '__main__':
    parser = TestGeneratorArgumentParser(tiling_arguments = True,
                                         description = "Deeploy XDNA2 Code Generation Utility.")
    parser.add_argument('--trace',
                        action = 'store_true',
                        default = False,
                        help = 'Enable execution tracing in the generated MLIR')
    parser.add_argument('--trace-buffer-size',
                        type = int,
                        default = 8192,
                        help = 'Trace buffer size in bytes (default: 8192)')
    parser.add_argument('--trace-shim-col',
                        type = int,
                        default = 7,
                        help = 'Shim column to egress trace packets through (default: 7, '
                        'the rightmost shim on npu2).')
    parser.add_argument('--trace-tiles',
                        type = str,
                        default = None,
                        help = 'Comma-separated tile selector for tracing, e.g. "c0r2,c1r2". '
                        'Only meaningful with --trace. If omitted, every active core is traced.')
    parser.add_argument('--num-col',
                        type = int,
                        default = 1,
                        help = f'Number of AIE columns to use (1..{NPU2_NUM_COLS}, default: 1).')
    parser.add_argument('--num-aie-row',
                        type = int,
                        default = 1,
                        help = f'Number of AIE compute rows per column to use (1..{NPU2_NUM_AIE_ROWS}, '
                        f'default: 1). Total active AIE compute tiles = num-col * num-aie-row.')
    parser.add_argument('--data-mode',
                        type = str,
                        choices = ['auto', 'embed', 'file'],
                        default = 'auto',
                        help = 'Where test inputs/outputs live. "embed" inlines them in the test '
                        'header (good for small tensors), "file" dumps them to .bin sidecars (needed '
                        'for >32 MiB tensors), "auto" picks per size (default).')
    args, _ = parser.parse_known_args()

    if args.platform != 'XDNA2':
        parser.error(f"This script is for the XDNA2 platform. Got: {args.platform}")

    generateNetworkXDNA2(args)
