name: TestRunnerSiracusa

on:
  workflow_call:
    inputs:
      runner:
        required: true
        type: string
      docker-image:
        required: true
        type: string
      test-names:
        required: true
        type: string
      num-cores:
        required: true
        type: number

jobs:
  test-runner-siracusa:
    runs-on: ${{ inputs.runner }}
    container:
      image: ${{ inputs.docker-image }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Build Deeploy
        run: pip install -e .
      - name: Cache ccache
        uses: actions/cache/restore@v4
        with:
          path: /app/.ccache
          key: ccache-ci
      - name: Run Test
        run: |
          testNames="${{ inputs.test-names }}"
          cd DeeployTest
          mkdir -p /app/.ccache
          export CCACHE_DIR=/app/.ccache
          echo "$testNames" | while IFS= read -r testName; do
            if [[ -n "$testName" ]]; then
              echo "Running test: $testName"
              python testRunner_siracusa.py -t Tests/$testName --cores=${{ inputs.num-cores }}
            fi
          done
        shell: bash
        